### ISSUE TITLE
Unable to verify credentials in v4.0.0

### ISSUE THREAD

**Issue by arulrajesh** [i-am-grub/MultiGP_Toolkit#8]
![multigp grub error](https://github.com/i-am-grub/MultiGP_Toolkit/assets/4302998/09283fcc-e394-45e6-8974-752fe6698436)

I know the timer has internet connection because I just used the CLI to update the plugin.

**Comment by i-am-grub** [comment]
I believe this was probably an issue with MultiGP's server, but lets keep it open for the time being in case it more people start to encounter this issue.

**Comment by i-am-grub** [comment]
Discovered that the RotorHazard database doesn't update with the entered value until after clicking outside of the textbox, so the database wasn't updated with the entered value by the time `Verify Credentials` was clicked.
